version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - auth-network

  ml-service:
    build: ./ml-python
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
