spring:
  application:
    name: secure-auth-system
  data:
    mongodb:
      uri: mongodb+srv://admin:adarshbgmi27@cluster0.ewsq9ts.mongodb.net/BiometricDB?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8080
